name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv lock -d > requirements.txt

      - name: Build Docker image
        run: |
          docker build -t ml-app .
          docker run -d -p 5000:5000 ml-app
          docker ps -a

      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ml-app:latest ${{ secrets.DOCKER_USERNAME }}/ml-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ml-app:latest

      - name: Deploy to Render
        if: github.ref == 'refs/heads/master'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST 'https://api.render.com/v1/servicessrv-cpsm2eqj1k6c738q7vi0/deploys' \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{"clearCache": false}'
